version: "3.3"

services:


  restchat_server:
    build: server
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/server
    env_file:
      - .env


  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
        - ./server/db/:/docker-entrypoint-initdb.d/
    env_file:
      - .env