version: "3.3"

services:
  server-balance:
    depends_on:
      - db 
    build: server
    ports:
      - 8000:8080
    volumes:
      - ./server/:/usr/src/server
    env_file:
      - .env


  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
        - ./server/db/sql/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
